#!/bin/bash

export OUTDIR="./posts"
export DATADIR="./data"
export MAXPERPAGE=10

export counter=0

export outcounter=0
export outfn="$OUTDIR/index.md"

rm -f $outfn
export prvbasefn='.'

while IFS='' read -r postfn || [[ -n "$postfn" ]] ; do
  echo "$postfn"

  if [[ "$counter" -ge 10 ]] ; then

    nxtcounter=`echo "$outcounter + 1" | bc`

    echo -e '\n\n' >> $outfn
    if [[ "$outcounter" -gt 0 ]] ; then
      #echo '[<<< previous posts]('$nxtcounter'/) &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [>>>]('$prvbasefn'/)' >> $outfn

      if [[ "$prvbasefn" == "." ]] ; then
        echo '[<<< previous posts]('$nxtcounter.html') &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [>>>](/)' >> $outfn
      else

        echo '[<<< previous posts]('$nxtcounter.html') &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [>>>]('$prvbasefn.html')' >> $outfn
      fi
      prvbasefn="$outcounter"
    else
      #echo '[<<< previous posts]('$nxtcounter'/)' >> $outfn
      echo '[<<< previous posts]('$nxtcounter.html')' >> $outfn
      prvbasefn="."
    fi
    echo -e '\n\n' >> $outfn

    #outcounter=`echo "$outcounter + 1" | bc`
    outcounter="$nxtcounter"
    counter=0
    nextoutfn="$OUTDIR/$outcounter.md"

    outfn=$nextoutfn

    rm -f "$outfn"

  fi
  echo $counter, $outcounter, $outfn, $prvbasefn

  cat $postfn >> $outfn
  echo -e "\n\n---\n\n" >> $outfn

  counter=`echo "$counter + 1" | bc`


done < <( find $DATADIR -maxdepth 1 -type f -regex ".*/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9].*[^~]$"  | sort -n -r )

# create final nex/previous links
#
echo -e '\n\n' >> $outfn
#echo ' &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [>>>]('$prvbasefn'/)' >> $outfn
echo ' &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [>>>]('$prvbasefn.html')' >> $outfn
echo -e '\n\n' >> $outfn

mkdocs build --clean


./post-process
