site_name: mechaesthetic
nav:
  - index.md
  - 1.md
  - 2.md
  - 3.md
  - 4.md
  - 5.md


docs_dir: 'posts'
use_directory_urls: false
theme:
  name: mkdocs
  custom_dir: 'theme'
extra:
  base : ""
  minitrack: "https://mechaelephant.com/minitrack/vampirepuff.svg"


